# Generated by Django 3.2.8 on 2022-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_doctorinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
