# Generated by Django 3.2.8 on 2022-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_approval_comment_department_doc_dep_doctorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='photo',
            field=models.CharField(max_length=4096),
        ),
    ]
