# Generated by Django 3.2.8 on 2022-06-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='claim_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publish_user',
        ),
        migrations.AlterField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_approval', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_comment', to='backend.user'),
        ),
        migrations.DeleteModel(
            name='LabelImg',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
