# Generated by Django 3.2.8 on 2022-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20220606_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approval',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Doc_Dep',
        ),
    ]
