# Generated by Django 3.2.8 on 2022-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20220606_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='score_sum',
            field=models.FloatField(default=0),
        ),
    ]
