# Generated by Django 3.2.8 on 2022-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20220606_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='photo',
            field=models.CharField(default='NULL', max_length=4096),
        ),
    ]
