# Generated by Django 3.2.8 on 2022-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20220606_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=64)),
                ('email', models.EmailField(default='123456789@gmail.com', max_length=254, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.UniqueConstraint(fields=('user_name', 'email'), name='unique_user'),
        ),
    ]
