# Generated by Django 3.2.8 on 2022-06-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20220606_1313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userinfo',
            name='unique_user',
        ),
    ]
