# Generated by Django 3.2.8 on 2022-06-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
