# Generated by Django 3.2.8 on 2022-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20220606_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='123456789@gmail.com', max_length=254, unique=True),
        ),
    ]
